// Sample data for the static demo build (VITE_DEMO). All dates are
// derived from "now" at load time so the board always looks alive —
// nothing here is personal data.

import { toLocalDateKey, type RecurringItem } from "../domain/recurrence";
import type { Task } from "../domain/task-rules";
import type { ShoppingItem, GroceryItem } from "../domain/entities";

const DAY_MS = 24 * 60 * 60 * 1000;

/** Local YYYY-MM-DD key `days` from today (negative = past). */
const dueIn = (days: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return toLocalDateKey(d);
};

/** ISO timestamp `days` ago. */
const ago = (days: number): string =>
  new Date(Date.now() - days * DAY_MS).toISOString();

export const demoTasks: Task[] = [
  {
    id: "demo-t1",
    title: "Book dentist appointment",
    done: false,
    status: "this-week",
    effort: "low",
    decisionLoad: "low",
    area: "health",
    dueDate: dueIn(1),
    createdAt: ago(6),
    completedAt: null,
    deletedAt: null,
    source: "board",
    sourceItemId: null,
  },
  {
    id: "demo-t2",
    title: "Plan Saturday hike with Sam",
    done: false,
    status: "this-week",
    effort: "medium",
    decisionLoad: "medium",
    area: "social",
    dueDate: dueIn(3),
    createdAt: ago(4),
    completedAt: null,
    deletedAt: null,
    source: "board",
    sourceItemId: null,
  },
  {
    id: "demo-t3",
    title: "Finish chapter 4 of the systems design book",
    done: false,
    status: "this-week",
    effort: "high",
    decisionLoad: "low",
    area: "learning",
    dueDate: null,
    createdAt: ago(3),
    completedAt: null,
    deletedAt: null,
    source: "board",
    sourceItemId: null,
  },
  {
    id: "demo-t4",
    title: "Submit expense report",
    done: false,
    status: "this-week",
    effort: "low",
    decisionLoad: "low",
    area: "career",
    dueDate: dueIn(5),
    createdAt: ago(2),
    completedAt: null,
    deletedAt: null,
    source: "board",
    sourceItemId: null,
  },
  {
    id: "demo-t5",
    title: "Sketch homepage ideas for portfolio site",
    done: false,
    status: "this-week",
    effort: "medium",
    decisionLoad: "high",
    area: "project",
    dueDate: null,
    createdAt: ago(2),
    completedAt: null,
    deletedAt: null,
    source: "board",
    sourceItemId: null,
  },
  {
    id: "demo-t6",
    title: "Renew car registration",
    done: false,
    status: "this-month",
    effort: "medium",
    decisionLoad: "low",
    area: "life-admin",
    dueDate: dueIn(12),
    createdAt: ago(8),
    completedAt: null,
    deletedAt: null,
    source: "board",
    sourceItemId: null,
  },
  {
    id: "demo-t7",
    title: "Research weekend pottery classes",
    done: false,
    status: "this-month",
    effort: "low",
    decisionLoad: "medium",
    area: "social",
    dueDate: null,
    createdAt: ago(7),
    completedAt: null,
    deletedAt: null,
    source: "board",
    sourceItemId: null,
  },
  {
    id: "demo-t8",
    title: "Set up automatic savings transfer",
    done: false,
    status: "this-month",
    effort: "low",
    decisionLoad: "high",
    area: "life-admin",
    dueDate: dueIn(20),
    createdAt: ago(5),
    completedAt: null,
    deletedAt: null,
    source: "board",
    sourceItemId: null,
  },
  {
    id: "demo-t9",
    title: "Plan trip for Mom's birthday",
    done: false,
    status: "future",
    effort: "high",
    decisionLoad: "high",
    area: "social",
    dueDate: dueIn(45),
    createdAt: ago(10),
    completedAt: null,
    deletedAt: null,
    source: "board",
    sourceItemId: null,
  },
  {
    id: "demo-t10",
    title: "Sign up for the spring 10K",
    done: true,
    status: "done",
    effort: "low",
    decisionLoad: "low",
    area: "health",
    dueDate: null,
    createdAt: ago(9),
    completedAt: ago(1),
    deletedAt: null,
    source: "board",
    sourceItemId: null,
  },
  {
    id: "demo-t11",
    title: "Update resume with new role",
    done: true,
    status: "done",
    effort: "medium",
    decisionLoad: "medium",
    area: "career",
    dueDate: null,
    createdAt: ago(12),
    completedAt: ago(2),
    deletedAt: null,
    source: "board",
    sourceItemId: null,
  },
  {
    id: "demo-t12",
    title: "Try that new ramen place",
    done: false,
    status: "trashed",
    effort: "low",
    decisionLoad: "low",
    area: "social",
    dueDate: null,
    createdAt: ago(15),
    completedAt: null,
    deletedAt: ago(3),
    source: "board",
    sourceItemId: null,
  },
];

export const demoShopping: ShoppingItem[] = [
  {
    id: "demo-s1",
    title: "Desk lamp",
    done: false,
    archived: false,
    category: "need",
    links: ["https://example.com/desk-lamp"],
    createdAt: ago(5),
    doneAt: null,
  },
  {
    id: "demo-s2",
    title: "Running shoes",
    done: false,
    archived: false,
    category: "need",
    links: [],
    createdAt: ago(4),
    doneAt: null,
  },
  {
    id: "demo-s3",
    title: "Noise-cancelling headphones",
    done: false,
    archived: false,
    category: "want",
    links: ["https://example.com/headphones"],
    createdAt: ago(3),
    doneAt: null,
  },
  {
    id: "demo-s4",
    title: "Water filter refills",
    done: true,
    archived: false,
    category: "need",
    links: [],
    createdAt: ago(8),
    doneAt: ago(1),
  },
  {
    id: "demo-s5",
    title: "Picture frames",
    done: true,
    archived: true,
    category: "want",
    links: [],
    createdAt: ago(20),
    doneAt: ago(14),
  },
];

export const demoGroceries: GroceryItem[] = [
  {
    id: "demo-g1",
    title: "Eggs",
    done: false,
    createdAt: ago(2),
    category: "task",
  },
  {
    id: "demo-g2",
    title: "Oat milk",
    done: true,
    createdAt: ago(2),
    category: "task",
  },
  {
    id: "demo-g3",
    title: "Spinach",
    done: false,
    createdAt: ago(1),
    category: "task",
  },
  {
    id: "demo-g4",
    title: "Tortillas",
    done: false,
    createdAt: ago(1),
    category: "task",
  },
  {
    id: "demo-g5",
    title: "Hot sauce",
    done: false,
    createdAt: ago(1),
    category: "task",
  },
];

export const demoRecurring: RecurringItem[] = [
  {
    id: "demo-r1",
    title: "Water the plants",
    frequency: "weekly",
    dayOfWeek: 0,
    repeatEvery: 1,
    repeatUnit: "week",
    repeatDays: [0],
    endsType: "never",
    endsOn: null,
    endsAfter: null,
    note: "",
    link: "",
    completedThisWeek: false,
    lastCompletedAt: null,
    dueDate: null,
    showEarlyDays: null,
    area: "life-admin",
    createdAt: ago(30),
    category: "task",
  },
  {
    id: "demo-r2",
    title: "Weekly meal prep",
    frequency: "weekly",
    dayOfWeek: 0,
    repeatEvery: 1,
    repeatUnit: "week",
    repeatDays: [0],
    endsType: "never",
    endsOn: null,
    endsAfter: null,
    note: "",
    link: "",
    completedThisWeek: true,
    lastCompletedAt: ago(1),
    dueDate: null,
    showEarlyDays: null,
    area: "health",
    createdAt: ago(30),
    category: "task",
  },
  {
    id: "demo-r3",
    title: "Deep-clean coffee maker",
    frequency: "long-term",
    dayOfWeek: null,
    repeatEvery: 3,
    repeatUnit: "month",
    repeatDays: [],
    endsType: "never",
    endsOn: null,
    endsAfter: null,
    note: "Vinegar run, then two water runs",
    link: "",
    completedThisWeek: false,
    lastCompletedAt: null,
    dueDate: dueIn(10),
    showEarlyDays: 14,
    area: "life-admin",
    createdAt: ago(40),
    category: "task",
  },
];

export const demoSettings: Record<string, unknown> = {
  showArea: true,
};
